### ISSUE TITLE
how to use FoldingFactorizationBasedRecommender

### ISSUE THREAD

**Issue by ChemsEddineBerbegue** [plista/kornakapi#29]
hey,
I tried many times to use the recommend er mentioned above with SvdPlusPlusrecommender implemented by mahout, but everytime i fail to get recommendation since i do not know how to pass parameters of the recommender and HOW to fold new users ( like totally new users, or an old user with new rated items).
could you share us a use example ?

* one of tries i create a persist factorization by svd++ recommender, i passed it to foldingfactorizationrecommender, I GOT an exception telling that the matrix is not singular.
any help please

**Comment by ChemsEddineBerbegue** [comment]
DataModel model= new FileDataModel(new File("src/u.data"));
	      //SVDPlusPlusFactorizer factorizer=new SVDPlusPlusFactorizer(model, 10, 10);
	      
		  ALSWRFactorizer factorizer= new ALSWRFactorizer(model, 10,0.05, 10);
	      
	      Factorization factorization= factorizer.factorize();
	      
	      EuclideanDistanceSimilarity eds = new EuclideanDistanceSimilarity(model);
	      CandidateItemsStrategy candidateItemsStrategy= new AllSimilarItemsCandidateItemsStrategy(eds);
	      PersistenceStrategy persistence = 
        		  new FilePersistenceStrategy(new File("src/test"));
	      persistence.maybePersist(factorization);
	      FoldingFactorizationBasedRecommender ffbr =new 
	    		  FoldingFactorizationBasedRecommender(model,candidateItemsStrategy,persistence);

* svd++ doesn't work, als seems good, any additional explanation about fold in new users ?

**Comment by KukumavMozolo** [comment]
U have to pass config file on startup: 
mvn -Dkornakapi.conf=/.../kornakapi.conf clean tomcat:run

About folding in new user, u can only make recommendations for users and items that already have a feature vector estimated. In case there is a new user you know nothing about(no associated item) then you cant apply the model to make predictions. However if you know at least one item about the user then you can try to estimate the users feature vector by that items feature vector.

**Comment by ChemsEddineBerbegue** [comment]
thank you very much for your reply is so useful, but I am not launching a tomcat server but using the recommender only locally for tests.  I created the code above there is not more exception of: singular matrix" related to the problem of the inability to compute the inverse matrix. 

* is it possible to update the model after a user rates new items ?

**Comment by KukumavMozolo** [comment]
Yes, that possible, the proper way would be to retrain the hole model,
however you could also just recalculate the user feature vector.

**Comment by KukumavMozolo** [comment]
Sorry i did not ment to close
